language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  nosetests --with-coverage --cover-tests --cover-erase --cover-package=threadedtree
branches:
  only:
    - master
after_success:
  coveralls
